#include "PWM.h"

void PWM_Init(void) 
{
  RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
    
  RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;
    
  GPIOA->MODER &= ~GPIO_MODER_MODE5;
	GPIOA->MODER |= GPIO_MODER_MODE5_1;
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED5;
	
  GPIOA->AFR[0] &= ~GPIO_AFRL_AFSEL5;
  GPIOA->AFR[0] |= GPIO_AFRL_AFSEL5_0;
    
  TIM2->CR1 &= ~TIM_CR1_DIR;
    
  TIM2->PSC = 7;
    
  TIM2->ARR = 4095;
    
	TIM2->CCMR1 |= TIM_CCMR1_OC1M_1;
  TIM2->CCMR1 |= TIM_CCMR1_OC1M_2;
  TIM2->CCMR1 |= TIM_CCMR1_OC1PE;
    
  TIM2->CCER |= TIM_CCER_CC1P;
  TIM2->CCER |= TIM_CCER_CC1E;
    
  TIM2->CCR1 |= 0;
    
  TIM2->CR1 |= TIM_CR1_CEN;
}
